apiVersion: v1
kind: Template
metadata:
        name: chris-job-template
objects:
    - apiVersion: batch/v1
      kind: Job
      metadata:
          name: ${jobid}
      spec:
          parallelism: 1
          completions: 1
          template:
              metadata:
                  name: cloudy
              spec:
                  containers:
                  - name: cloudy
                    env:
                    - name: WORKDIR
                      value: /var/run/chris  
                    image: ${imageid}
                    volumeMounts:
                    - mountPath: /var/run/chris
                      name: image-storage    
                  restartPolicy: Never
                  volumes: 
                  - name: image-storage
                    persistentVolumeClaim:
                        claimName: ${jobid}
parameters: 
- description: job id
  name: jobid
- description: image id
  name: imageid